config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations'}

  resources :users, only: [:show]
  resources :symptoms

  root 'home#index'
  get 'pages/home'

  get "/", to:"home#index"
  get "/users", to:"user#index"
  get "/users/show", to:"users#show"
  get "/symptoms", to:"symptoms#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
  has_many :symptoms
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :symptoms

  def all_my_symptoms(symptom_id)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:current_user_id] = @user.id
  end

  def destroy

  end

end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
  def show
    @symptoms= Symptom.all
    @symptom_user = @symptom.user
  end

  def index
    @symptoms= Symptom.all

  end

  def new
  end

  def update
  end

  def destroy
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @current_user = User.find_by_id(session[:current_user_id])
    @symptoms = @user.symptoms
  end

  def index
    @users = User.all
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||=Devise.mappings[:user]
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/symptom_helper.rb
module SymptomHelper
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>index</h1>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active">
                <%= link_to "User", users_path%>
              </li>
              <li><a href="#">Calendar</a></li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Symptoms <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <a class="navbar-brand navbar-right" href="#">Pain Tracker</a>
            <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to current_user.name, current_user %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>

          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paintracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/oldregistrations/new.html.erb
<h2>Sign Up</h2>
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>
  
<% end %>

app/views/pages/_navbar.htm.erb
<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
              <li><a href="../navbar-static-top/">Static top</a></li>
              <li><a href="../navbar-fixed-top/">Fixed top</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/pages/home.html.erb
<h1>hello</h1>

app/views/symptoms/_symptomcard.html.erb
<% @symptoms.each do |s| %>
<div class="container symptomcard">
  <h3>Location: <%= s.location%></h3>
  <li><%=s.user.name%></li>
  <li>Severity: <%=s.severity%></li>
  <li>Kind: <%=s.kind%></li>
  <li>
  </li>

</div>
<% end %>

app/views/symptoms/index.html.erb
<%= render 'symptomcard' %>

app/views/users/_calendar.html.erb
calendar

<div class="container">
  <div class="row">
    <div class="day col-md-1">
      Sunday
    </div>
    <div class="day col-md-1">
      Monday
    </div>
    <div class="day col-md-1">
      Tuesday
    </div>
    <div class="day col-md-1">
      Wednesday
    </div>
    <div class="day col-md-1">
      Thursday
    </div>
    <div class="day col-md-1">
      Friday
    </div>
    <div class="day col-md-1">
      Saturday
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |u| %>
  <p>
    <h3><%= u.name %></h3>
    <li><%=u.email%></li>
    <li><%= u.id %></li>
    <li><%=u.password%></li>
  
  </p>
<% end %>

app/views/users/show.html.erb
<h1>seems to work</h1>
<%=@current_user_id %>
<%= render 'calendar' %>
<%= render '/symptoms/symptomcard' %>